
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.DrawingArea drawingarea;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w1.Position = 0;
		w1.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.drawingarea = new global::Gtk.DrawingArea();
		this.drawingarea.Events = ((global::Gdk.EventMask)(768));
		this.drawingarea.Name = "drawingarea";
		this.vbox2.Add(this.drawingarea);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.drawingarea]));
		w2.Position = 1;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.drawingarea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnDrawingareaButtonPressEvent);
		this.drawingarea.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnDrawingareaButtonReleaseEvent);
	}
}
